FROM unicon/shibboleth-idp:3.3.1

MAINTAINER jgasper@unicon.net

COPY shibboleth-idp/ /opt/shibboleth-idp

ADD https://github.com/Unicon/shib-cas-authn/releases/download/v3.3.0/cas-client-core-3.4.1.jar /opt/shibboleth-idp/webapp/WEB-INF/lib
